import{S as q,i as g,a as h}from"./assets/vendor-c493984e.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const $=document.querySelector(".gallery-container"),x=new q(".gallery a",{captionDelay:250,captionsData:"alt",captionPosition:"bottom"});function y(e){const i=e.map(({webformatURL:a,largeImageURL:n,tags:t,likes:r,views:c,comments:v,downloads:w})=>`<ul class="gallery-card">
      <li class="gallery">
      <a class="gallery-link" href="${n}"> 
   <img src="${a}" alt="${t}" width="270" height="160"/>
   </a>
    <div class="discrabe">
  <ul class="discrabe-list">
  <li class="discrabe-item"><b>Likes</b> ${r}</li>
  <li class="discrabe-item"><b>Views</b> ${c}</li>
  <li class="discrabe-item"><b>Comments</b> ${v}</li>
  <li class="discrabe-item"><b>Downloads</b> ${w}</li>
  </ul>
</div>
</li>
    </ul>`).join("");if($.insertAdjacentHTML("beforeend",i),e.length===0)return l(),d();x.refresh(),l()}function p(){const e=document.querySelector(".loading");e.style.display="flex"}function l(){const e=document.querySelector(".loading");e.style.display="none"}function d(e){g.error({position:"topRight",title:"",message:"Sorry, there are no images matching your search query. Please try again!"})}const b="is-hidden";function f(e){e.classList.add(b)}function M(e){e.classList.remove(b)}function L(e){e.disabled=!0}function P(e){e.disabled=!1}h.defaults.baseURL="https://pixabay.com/api";async function S({q:e="",page:i=1,per_page:a=15}){const n="44848974-7ecdee37a41921c1b33ea19fc",t=new URLSearchParams({key:n,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:a});return(await h.get(`?${t.toString()}`)).data}const O=document.querySelector(".search-form"),m=document.querySelector(".gallery-container");document.querySelector(".loading");const o=document.querySelector(".btn-load"),s={q:"",page:1,per_page:15,maxPage:0};f(o);O.addEventListener("submit",E);async function E(e){e.preventDefault(),m.innerHTML="",s.page=1;const i=e.currentTarget;if(s.q=i.elements.insert.value.toLowerCase().trim(),!s.q)return l(),d();p(),M(o),L(o);try{const{hits:a,totalHits:n}=await S(s);y(a),s.maxPage=Math.ceil(n/s.per_page),a.length>0&&a.length!==n?(P(o),o.removeEventListener("click",u),o.addEventListener("click",u)):f(o);const t=m.getBoundingClientRect().height*2;window.scrollBy({top:t,behavior:"smooth"})}catch{d()}i.reset()}async function u(){s.page+=1,L(o),p();try{const{hits:e}=await S(s);y(e)}catch{d()}finally{l(),P(o),s.page===s.maxPage&&(f(o),o.removeEventListener("click",u),g.info({position:"topRight",title:"",message:"We are sorry, but you have reached the end of search results."}))}}
//# sourceMappingURL=commonHelpers.js.map
