import{S as v,i as m,a as g}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const $=document.querySelector(".gallery-container");function h(e){const o=e.map(({webformatURL:i,largeImageURL:n,tags:t,likes:r,views:c,comments:w,downloads:q})=>`<ul class="gallery-card">
      <li class="gallery">
      <a class="gallery-link" href="${n}"> 
   <img src="${i}" alt="${t}" width="270" height="160"/>
   </a>
    <div class="discrabe">
  <ul class="discrabe-list">
  <li class="discrabe-item"><b>Likes</b> ${r}</li>
  <li class="discrabe-item"><b>Views</b> ${c}</li>
  <li class="discrabe-item"><b>Comments</b> ${w}</li>
  <li class="discrabe-item"><b>Downloads</b> ${q}</li>
  </ul>
</div>
</li>
    </ul>`).join("");if($.insertAdjacentHTML("beforeend",o),e.length===0)return l(),d();new v(".gallery a",{captionDelay:250,captionsData:"alt",captionPosition:"bottom"}).refresh(),l()}function y(){const e=document.querySelector(".loading");e.style.display="flex"}function l(){const e=document.querySelector(".loading");e.style.display="none"}function d(e){m.error({position:"topRight",title:"",message:"Sorry, there are no images matching your search query. Please try again!"})}const p="is-hidden";function u(e){e.classList.add(p)}function M(e){e.classList.remove(p)}function b(e){e.disabled=!0}function L(e){e.disabled=!1}g.defaults.baseURL="https://pixabay.com/api";async function P({q:e="",page:o=1,per_page:i=15}){const n="44848974-7ecdee37a41921c1b33ea19fc",t=new URLSearchParams({key:n,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:i});return(await g.get(`?${t.toString()}`)).data}const O=document.querySelector(".search-form"),f=document.querySelector(".gallery-container");document.querySelector(".loading");const s=document.querySelector(".btn-load"),a={q:"",page:1,per_page:15,maxPage:0};u(s);O.addEventListener("submit",x);async function x(e){e.preventDefault(),f.innerHTML="",a.page=1;const o=e.currentTarget;if(a.q=o.elements.insert.value.toLowerCase().trim(),!a.q)return l(),d();y(),M(s),b(s);try{const{hits:i,totalHits:n}=await P(a);h(i),a.maxPage=Math.ceil(n/a.per_page),i.length>0&&i.length!==n?(L(s),s.addEventListener("click",S)):u(s);const t=f.getBoundingClientRect().height*2;window.scrollBy({top:t,behavior:"smooth"})}catch{d()}o.reset()}async function S(){a.page+=1,b(s),y();try{const{hits:e}=await P(a);h(e)}catch{d()}finally{l(),L(s),a.page===a.maxPage&&(u(s),s.removeEventListener("click",S),m.info({position:"topRight",title:"",message:"We are sorry, but you have reached the end of search results."}))}}
//# sourceMappingURL=commonHelpers.js.map
